name: duck_shop
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bloc: ^1.0.0
  flutter_bloc: ^1.0.0
  equatable: ^0.6.1
  uuid: ^2.0.2
  shared_preferences: ^0.5.4
  http: ^0.12.0
  image_picker: ^0.6.1+10
  firebase_ml_vision: ^0.9.2+2
  firebase_core: ^0.4.0+9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
